name: Render manifests
on:
  push:
    branches:
      - main

jobs:
  render-manifests:
    name: Render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [int, tst, prd]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2

      - name: Check for live branch
        run: |
          LIVE_BRANCH="live-${{ matrix.env }}/grafana"
          if ! git ls-remote --heads origin $LIVE_BRANCH | grep -q $LIVE_BRANCH; then
            git checkout --orphan $LIVE_BRANCH
            git rm -rf . || true
            echo "# Live manifests for ${{ matrix.env }}/grafana" > README.md
            git add README.md
            git commit -m "Initialize live branch for ${{ matrix.env }}/grafana"
            git push --set-upstream origin $LIVE_BRANCH
          fi
          echo "LIVE_BRANCH=$LIVE_BRANCH" >> $GITHUB_ENV

      - name: Render manifests
        run: |
          PREVIEW_BRANCH="preview-${{ matrix.env }}/grafana-${GITHUB_RUN_NUMBER}"

          git checkout -b "$PREVIEW_BRANCH" origin/main

          kustomize build ${{ matrix.env }}/grafana --enable-helm > rendered-manifests.yaml

          git add rendered-manifests.yaml
          git commit -m "Render manifests for ${{ matrix.env }}/grafana"
          git push --set-upstream origin $PREVIEW_BRANCH
          echo "PREVIEW_BRANCH=$PREVIEW_BRANCH" >> $GITHUB_ENV

      - name: Create PR
        run: |

          gh pr create \
            --title "Update ${{ matrix.env }}/grafana manifests" \
            --body "**Automated manifest update**
            
            This PR contains rendered manifests for ${{ matrix.env }}/grafana environment.
            
            **Source commit:** ${{ github.sha }}
            **Commit message:** ${{ github.event.head_commit.message }}
            
            Please review the changes before merging to deploy to the live environment." \
            --base $LIVE_BRANCH \
            --head $PREVIEW_BRANCH \

        env:
          GH_TOKEN: ${{ secrets.DEPLOY_PAT }}
