name: Render manifests
on:
  push:
    branches:
      - main

jobs:
  render-manifests:
    name: Render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [int, tst, prd]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          fetch-depth: 0

      - uses: fregante/setup-git-user@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Configure Git and remote with PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_PAT }}@github.com/${{ github.repository }}

      - name: Render manifests and push to PR branch
        run: |
          BASE_BRANCH="${{ matrix.env }}/grafana"
          PR_BRANCH="rendered/${BASE_BRANCH}-$(date +%s)"

          # Render
          kustomize build ${{ matrix.env }}/grafana --enable-helm > /tmp/all.yaml

          # Create temp PR branch
          git checkout -b "$PR_BRANCH"

          cp /tmp/all.yaml all.yaml
          git add all.yaml
          git commit -m "Rendered manifests for $BASE_BRANCH"
          git push origin "$PR_BRANCH"

          echo "pr_branch=$PR_BRANCH" >> $GITHUB_ENV
          echo "base_branch=$BASE_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}
        run: |
          gh pr create \
            --head "$pr_branch" \
            --base "$base_branch" \
            --title "Rendered manifests update for $base_branch" \
            --body "This PR contains the latest rendered manifests for the $base_branch environment."
