name: Render manifests
on:
  push:
    branches:
      - main

jobs:
  render-manifests:
    name: Render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [int, tst, prd]

    steps:
      - uses: actions/checkout@v3
      - name: Render manifests
        run: |
          kustomize build grafana/${{ matrix.env }} > /tmp/all.yaml
          if ! git checkout grafana/${{ matrix.env }} -- ; then
            git checkout --orphan grafana/${{ matrix.env }}
            git rm -rf .
            cp /tmp/all.yaml .
            git add .
            git commit -m "${{ github.event.head_commit.message }}"
            git push --set-upstream origin grafana/${{ matrix.env }}
          else
            cp /tmp/all.yaml .
          fi
      - name: Deploy to ${{ matrix.env }}
        run: |
          if ! git diff --quiet HEAD ; then 
            git add .
            git commit -m "${{ github.event.head_commit.message }}"
            git push --set-upstream origin grafana/${{ matrix.env }}
          fi
