name: Render manifests
on:
  push:
    branches:
      - main

jobs:
  render-manifests:
    name: Render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [int, tst, prd]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2

      - name: Check for live branch
        run: |
          LIVE_BRANCH="live/${{ matrix.env }}"
          if ! git ls-remote --heads origin $LIVE_BRANCH | grep -q $LIVE_BRANCH; then
            git checkout --orphan $LIVE_BRANCH
            git rm -rf .
            echo "# Live manifests for ${{ matrix.env }}" > README.md
            git add README.md
            git commit -m "Initialize live branch for ${{ matrix.env }}"
            git push --set-upstream origin $LIVE_BRANCH
          fi
          echo "LIVE_BRANCH=$LIVE_BRANCH" >> $GITHUB_ENV

      - name: Render manifests
        run: |
          PREVIEW_BRANCH="preview/${{ matrix.env }}-${GITHUB_RUN_NUMBER}"

          git fetch origin $LIVE_BRANCH
          git checkout -b "$PREVIEW_BRANCH" origin/"$LIVE_BRANCH"

          git worktree add ../main-worktree origin/main
          for dir in ./main-worktree/${{ matrix.env }}/*/; do
            app_name=$(basename "$dir")
            mkdir -p "$dir"
            echo "Rendering manifests for $app_name"
            kustomize build "$dir" --enable-helm > "$dir/rendered-manifests.yaml"
          done
          git worktree remove ../main-worktree --force

          git add .
          git commit -m "Render manifests for ${{ matrix.env }}"
          git push --set-upstream origin $PREVIEW_BRANCH
          echo "PREVIEW_BRANCH=$PREVIEW_BRANCH" >> $GITHUB_ENV

      - name: Create PR
        run: |
          if ! git diff --quiet origin/$LIVE_BRANCH..HEAD ; then 
            gh pr create \
              --title "Update live/${{ matrix.env }} manifests" \
              --body "**Automated manifest update**
              
              This PR contains rendered manifests for ${{ matrix.env }} environment.
              
              **Source commit:** ${{ github.sha }}
              **Commit message:** ${{ github.event.head_commit.message }}
              
              Please review the changes before merging to deploy to the live environment." \
              --base $LIVE_BRANCH \
              --head $PREVIEW_BRANCH
          else
            echo "No changes detected for live/${{ matrix.env }}"
            # Clean up review branch if no changes
            git push origin --delete $PREVIEW_BRANCH || true
          fi

        env:
          GH_TOKEN: ${{ secrets.DEPLOY_PAT }}
