name: Render manifests
on:
  push:
    branches:
      - main

jobs:
  render-manifests:
    name: Render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [int, tst, prd]

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - name: Render manifests
        run: |
          kustomize build ${{ matrix.env }}/grafana --enable-helm > /tmp/all.yaml
          if ! git checkout ${{ matrix.env }}/grafana -- ; then
            git checkout --orphan ${{ matrix.env }}/grafana
            git rm -rf .
            cp /tmp/all.yaml .
            git add .
            git commit -m "${{ github.event.head_commit.message }}"
            git push --set-upstream origin ${{ matrix.env }}/grafana
          else
            cp /tmp/all.yaml .
          fi
      - name: Deploy to ${{ matrix.env }}
        run: |
          if ! git diff --quiet HEAD ; then 
            git add .
            git commit -m "${{ github.event.head_commit.message }}"
            git push --set-upstream origin ${{ matrix.env }}/grafana
          fi
